version: '3'
services: 
    db: 
        image: mysql:8.0
        platform: linux/x86_64
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: root
        ports: 
            - "3306:3306"
        volumes: 
            - ./initdb.d:/docker-entrypoint-initdb.d

    web:
        build: .
        command: rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/app_name
        ports:
            - "3000:3000"
        links: 
            - db